<?php

/**
 * @file
 * Code for the Outsell workflow content types feature.
 */

include_once 'outsell_sharing.features.inc';

/**
 * Implements hook_menu().
 */
function outsell_sharing_menu() {

  // Settings for sharing.
  $menu['admin/config/outsell/sharing'] = array(
    'title' => 'Sharing',
    'description' => 'Settings around content sharing.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('outsell_sharing_settings_form'),
    'file' => 'outsell_sharing.admin.inc',
    'file path' => drupal_get_path('module', 'outsell_sharing'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer site configuration'),
  );

  return $menu;
}

/**
 * Implements hook_permission().
 */
function outsell_sharing_permission() {
  return array(
    'access all segments' => array(
      'title' => t('Access all segments'),
    ),
    'access b2b segments' => array(
      'title' => t('Access all b2b segments'),
    ),
    'access cnf-grc segments' => array(
      'title' => t('Access all cnf/grc segments'),
    ),
    'access ent segments' => array(
      'title' => t('Access all ent segments'),
    ),
    'access library segments' => array(
      'title' => t('Access all library segments'),
    ),
    'access ltr-grc segments' => array(
      'title' => t('Access all ltr/grc segments'),
    ),
    'access stm segments' => array(
      'title' => t('Access all stm segments'),
    ),
    'access mm segments' => array(
      'title' => t('Access all marketing-media (mm) segments'),
    ),
  );
}

/**
 * Implements hook_segment_explorer_segments_preprocess().
 */
function outsell_sharing_segment_explorer_segments_preprocess($segments) {
  $mapping = variable_get('segment_mapping', array());

  foreach ($segments as $key => $row) {
    $access = FALSE;

    if (user_access('access all segments') == TRUE && in_array(strtolower($row['short_name']), $mapping['all'])) {
      $access = TRUE;
    }
    if (user_access('access b2b segments') == TRUE && in_array(strtolower($row['short_name']), $mapping['b2b'])) {
      $access = TRUE;
    }
    if (user_access('access cnf-grc segments') == TRUE && in_array(strtolower($row['short_name']), $mapping['c&f/grc'])) {
      $access = TRUE;
    }
    if (user_access('access ent segments') == TRUE && in_array(strtolower($row['short_name']), $mapping['e&t'])) {
      $access = TRUE;
    }
    if (user_access('access library segments') == TRUE && in_array(strtolower($row['short_name']), $mapping['liberty'])) {
      $access = TRUE;
    }
    if (user_access('access ltr-grc segments') == TRUE && in_array(strtolower($row['short_name']), $mapping['ltr/grc'])) {
      $access = TRUE;
    }
    if (user_access('access stm segments') == TRUE && in_array(strtolower($row['short_name']), $mapping['stm'])) {
      $access = TRUE;
    }
    if (user_access('access mm segments') == TRUE && in_array(strtolower($row['short_name']), $mapping['marketing&media'])) {
      $access = TRUE;
    }
    if ($access == FALSE) {
      unset($segments[$key]);
    }
  }

  return $segments;
}
